application: invite-voiceflows
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /font-awesome-4.1.0
  static_dir: font-awesome-4.1.0
- url: /template
  static_dir: emails/

- url: .*
  script: main.app



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: latest