application: invite-voiceflows
version: 3
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- deferred: on

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /font-awesome-4.1.0
  static_dir: static/font-awesome-4.1.0
- url: /template
  static_dir: templates/

- url: .*
  script: main.app



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"