from .UpdateOrCreateContactCommand import UpdateOrCreateContactCommand
from .DeleteContactCommand import DeleteContactCommand
from .UpdateAttendeeAttachToContactCommand import UpdateAttendeeAttachToContactCommand